name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Faz checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3
      # Passo 2: Instala o Mocha
      - name: Install dependencies (mocha)
        run: npm install mocha
      # Passo 3: Executa os testes
      - name: start
        run: node src/index.js
      - name: test
        run: mocha test/validacao.js